#!/usr/bin/env bash
set -e

CGO_ENABLED=0

OUTPUT=${OUTPUT:-bin/hbm}

source $(dirname $0)/version

GITSTATE="clean"
if [ -n "$DIRTY" ]; then
	GITSTATE="dirty"
fi

CONST="-X github.com/jonasbroms/hbm/version.Version=${VERSION} -X github.com/jonasbroms/hbm/version.GitCommit=${COMMIT} -X github.com/jonasbroms/hbm/version.GitState=${GITSTATE} -X github.com/jonasbroms/hbm/version.BuildDate=$(date +%s)"

LDFLAGS=${LDFLAGS:-"-linkmode external -extldflags -static -s -w"}

cd $(dirname $0)/..

echo " Building ${VERSION} from ${COMMIT} on ${ARCH}"

go build -ldflags "${CONST} ${LDFLAGS}" -o ${OUTPUT}
strip --strip-all ${OUTPUT}
echo "Built ${OUTPUT}"
